version: '3.8'

services:
  backend:
    image: backend:latest
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
